### ISSUE TITLE
Problems with deployment as azure webapp

### ISSUE THREAD

**Issue by sanderkooger** [imazen/imageflow#481]
First off Thank you for building imageflow.

For a project that a group of coding students is working on we are looking to deploy imageflow_server. The idea is to store images in azure blobstorage, expose them via imageflow_server in a container, and then cache withing Azure CDN. 

In my local test environment i have a container running and i am able to resize images with this compose file. 
```
version: "3.3"

services:
  imageflow:
    entrypoint: '/bin/sh -c "sudo chown -R imageflow /home/imageflow/ && /home/imageflow/imageflow_server start --mount "/tifimages/:ir4_http:https:://tifimages.blob.core.windows.net/" --bind-address 0.0.0.0 --port 3000 --data-dir /home/imageflow/data/"'
    environment:
      - RUST_BACKTRACE=1
    image: "imazen/imageflow_server_unsecured:latest"
    ports:
      - "80:3000"
    volumes:
      - "imageflow_data:/home/imageflow/data"
volumes:
  imageflow_data:

```

Bu i seem to be unable to run the same on Azure webapps. 

My question is is there a way to deploy contaienr only and use env variables to configure the mountpoints? This woudl highly improve compatibility with services like this.

**Comment by lilith** [comment]
What error message are you getting?

**Comment by sanderkooger** [comment]
Hey @lilith thank you, 

Yes the moment we deploy using above yml on azure webapps, we get the following errorlog
```
Starting Log Tail -n 10 of existing logs ----
/appsvctmp/volatile/logs/runtime/f76ac1fa531f9e263817464e080b9f31c15380cb976a71b1eaff9ae3fb1e1de0.log
2020-07-07T12:08:43.799354311Z: [ERROR]  error: Found argument '--mount' which wasn't expected, or isn't valid in this context
2020-07-07T12:08:43.799414713Z: [ERROR]
2020-07-07T12:08:43.799425113Z: [ERROR]  USAGE:
2020-07-07T12:08:43.799433213Z: [ERROR]      imageflow_server <SUBCOMMAND>
2020-07-07T12:08:43.799441313Z: [ERROR]
2020-07-07T12:08:43.801511967Z: [ERROR]  For more information try --help
```

The YML works locally with docker compose up.

**Comment by iuriikomarov** [comment]
@sanderkooger it looks like a mess with quotes in your `entrypoint`

You open double quote after `/bin/sh -c ` and close it after `--mount` so your command passing by to docker is `/bin/sh -c "sudo chown -R imageflow /home/imageflow/ && /home/imageflow/imageflow_server start --mount `

**Comment by sanderkooger** [comment]
Hey @iuriikomarov  thank you for your answer, 

I have modified the below example to test but still the same problem. 
https://github.com/imazen/imageflow/blob/main/docker/imageflow_server_unsecured/docker-compose.yml

```
version: "3.3"

services:
  imageflow:
    entrypoint: '/bin/sh -c "sudo chown -R imageflow /home/imageflow/ && /home/imageflow/imageflow_server start --demo --bind-address 0.0.0.0 --port 3000 --data-dir /home/imageflow/data/"'
    environment:
      - RUST_BACKTRACE=1
    image: "imazen/imageflow_server_unsecured:latest"
    ports:
      - "3000:3000"
    volumes:
      - "imageflow_data:/home/imageflow/data"
volumes:
  imageflow_data:
```

I am getting below error
Connecting...
2020-07-08T17:19:10  Welcome, you are now connected to log-streaming service.
Starting Log Tail -n 10 of existing logs ----
/appsvctmp/volatile/logs/runtime/6e325ac664158ab1cb637f25d7189c41387d1f2fea2a76090aa334529c32cff1.log
2020-07-08T17:18:59.792054210Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
2020-07-08T17:18:59.792054210Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
2020-07-08T17:19:03.075903722Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
2020-07-08T17:18:59.792054210Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
2020-07-08T17:19:03.075903722Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
2020-07-08T17:19:06.818121174Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
/appsvctmp/volatile/logs/runtime/8f1b84228573ee75f3d34a189b60972930255332374c4389568f2989af214191.log
2020-07-08T17:17:13.089047839Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
2020-07-08T17:17:13.089047839Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
2020-07-08T17:17:19.781009165Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
2020-07-08T17:17:13.089047839Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
2020-07-08T17:17:19.781009165Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
2020-07-08T17:17:22.313810420Z: [ERROR]  chown: 1: chown: Syntax error: Unterminated quoted string
Ending Log Tail of existing logs ---
Starting Live Log Stream ---

**Comment by lilith** [comment]
You should be able to drop the chown statement with the most recent build per https://github.com/imazen/imageflow/commit/66028603aeae6d9666bbfb7da83e026c14a8a660

This should solve the quotes problem indirectly.

**Comment by sanderkooger** [comment]
Hey @lilith, 

I tried with below docker-compose.yml
```
version: "3.3"

services:
  imageflow:
    entrypoint: '/bin/sh -c "/home/imageflow/imageflow_server start --demo --bind-address 0.0.0.0 --port 3000 --data-dir /home/imageflow/data/"'
    environment:
      - RUST_BACKTRACE=1
    image: "imazen/imageflow_server_unsecured:latest"
    ports:
      - "8080:3000"
    volumes:
      - "imageflow_data:/home/imageflow/data"
volumes:
  imageflow_data:
```

It generated the following error on my local environment
```
Open your browser to http://0.0.0.0:3000/proxied_demo/index.html
built 13 hours ago - unofficial CI release build of v1.4.10-rc50-6-gbd72a01* (main) for x86_64-unknown-linux-gnu  (2020-07-11)
Listening on 0.0.0.0:3000
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', imageflow_server/src/disk_cache.rs:143:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1268
  14: core::result::Result<T,E>::unwrap
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/result.rs:1005
  15: imageflow_server::disk_cache::CacheFolder::prepare_for
             at imageflow_server/src/disk_cache.rs:143
  16: imageflow_server::disk_cache::CacheEntry::prepare_dir
             at imageflow_server/src/disk_cache.rs:179
  17: imageflow_server::disk_cache::CacheEntry::write
             at imageflow_server/src/disk_cache.rs:191
  18: imageflow_server::fetch_bytes_using_cache_by_url
             at imageflow_server/src/lib.rs:203
  19: imageflow_server::permacache_proxy_handler_guess_types
             at imageflow_server/src/lib.rs:486
  20: imageflow_server::mount::{{closure}}
             at imageflow_server/src/lib.rs:564
  21: <F as iron::middleware::Handler>::handle
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:312
  22: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
  23: <mount::mount::Mount as iron::middleware::Handler>::handle
             at ./.cargo/git/checkouts/mount-e3fe55b55b7ad7b2/2c3d719/src/mount.rs:122
  24: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
  25: iron::middleware::Chain::continue_from_handler
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:282
  26: iron::middleware::Chain::continue_from_before
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:276
  27: <iron::middleware::Chain as iron::middleware::Handler>::handle
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:200
  28: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/iron.rs:176
  29: hyper::server::Worker<H>::keep_alive_loop
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:340
  30: hyper::server::Worker<H>::handle_connection
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:282
  31: hyper::server::handle::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:242
  32: hyper::server::listener::spawn_with::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/listener.rs:50
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lilith** [comment]
That's odd. Are you sure you've cleared the cache and are pulling the
latest docker image?

**Comment by sanderkooger** [comment]
I did, Image was only 2 hours old. 

I cleared cache to test and it still did the same. (unofficial CI release build of v1.4.10-rc50-6-gbd72a01* (main) for x86_64-unknown-linux-gnu )

I tried today removing the image from my cache with below compose file
```
imageflow:
  entrypoint: '/bin/sh -c "/home/imageflow/imageflow_server start --demo --bind-address 0.0.0.0 --port 3000 --data-dir /home/imageflow/data/"'
  environment:
    - RUST_BACKTRACE=1
  image: "imazen/imageflow_server_unsecured:latest"
  ports:
    - "8080:3000"
  volumes:
    - "imageflow_data:/home/imageflow/data"

```

when i load the demo site in my browser i recieve following error. 
```
sander@TIF-NB-001:~/tif-repos/code/imageflow/docker/imageflow_server_unsecured$ docker logs -f 44e7b0b59f2359194a157ac7bc7325234b82de02351e0ad3935ebeeab432865e
Open your browser to http://0.0.0.0:3000/proxied_demo/index.html
built 2 days ago - unofficial CI release build of v1.4.10-rc50-6-gbd72a01* (main) for x86_64-unknown-linux-gnu  (2020-07-11)
Listening on 0.0.0.0:3000
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', imageflow_server/src/disk_cache.rs:143:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1268
  14: core::result::Result<T,E>::unwrap
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/result.rs:1005
  15: imageflow_server::disk_cache::CacheFolder::prepare_for
             at imageflow_server/src/disk_cache.rs:143
  16: imageflow_server::disk_cache::CacheEntry::prepare_dir
             at imageflow_server/src/disk_cache.rs:179
  17: imageflow_server::disk_cache::CacheEntry::write
             at imageflow_server/src/disk_cache.rs:191
  18: imageflow_server::fetch_bytes_using_cache_by_url
             at imageflow_server/src/lib.rs:203
  19: imageflow_server::permacache_proxy_handler_guess_types
             at imageflow_server/src/lib.rs:486
  20: imageflow_server::mount::{{closure}}
             at imageflow_server/src/lib.rs:564
  21: <F as iron::middleware::Handler>::handle
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:312
  22: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
  23: <mount::mount::Mount as iron::middleware::Handler>::handle
             at ./.cargo/git/checkouts/mount-e3fe55b55b7ad7b2/2c3d719/src/mount.rs:122
  24: <alloc::boxed::Box<dyn iron::middleware::Handler> as iron::middleware::Handler>::handle
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
  25: iron::middleware::Chain::continue_from_handler
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:282
  26: iron::middleware::Chain::continue_from_before
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:276
  27: <iron::middleware::Chain as iron::middleware::Handler>::handle
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:200
  28: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/iron.rs:176
  29: hyper::server::Worker<H>::keep_alive_loop
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:340
  30: hyper::server::Worker<H>::handle_connection
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:282
  31: hyper::server::handle::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:242
  32: hyper::server::listener::spawn_with::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/listener.rs:50
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sanderkooger** [comment]
Im also unable to build the image itself with the dockerfile. 

```
sander@TIF-NB-001:~/tif-repos/code/imageflow/docker/imageflow_server_unsecured$ docker build --build-arg SOURCE_COMMIT=6602860 --tag imazen/imageflow_server_unsecured:latest .
[+] Building 2.8s (6/7)                                                                                                                                                      
 => [internal] load .dockerignore                                                                                                                                       0.1s
 => => transferring context: 2B                                                                                                                                         0.0s
 => [internal] load build definition from Dockerfile                                                                                                                    0.1s
 => => transferring dockerfile: 651B                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/imazen/imageflow_base_os:latest                                                                                              1.1s
 => CACHED [1/4] FROM docker.io/imazen/imageflow_base_os@sha256:1575c5707f7a09c45711328783c2cbfae4160ba8fc14ecef9d161a8e9da5750f                                        0.0s
 => [2/4] RUN if [ -z "6602860" ]; then echo "SOURCE_COMMIT not set; exiting" && exit 1; else echo "SOURCE_COMMIT=6602860"; fi                                          0.4s
 => ERROR [3/4] RUN mkdir nightly && cd nightly && wget -nv -O ifs.tar.gz https://s3-us-west-1.amazonaws.com/imageflow-nightlies/commits/6602860/linux64_glibc227.tar.  1.2s
------
 > [3/4] RUN mkdir nightly && cd nightly && wget -nv -O ifs.tar.gz https://s3-us-west-1.amazonaws.com/imageflow-nightlies/commits/6602860/linux64_glibc227.tar.gz     && tar xvzf ifs.tar.gz && mv ./imageflow_server ../ && cd .. && rm -rf nightly:
#6 1.167 https://s3-us-west-1.amazonaws.com/imageflow-nightlies/commits/6602860/linux64_glibc227.tar.gz:
#6 1.167 2020-07-14 16:40:03 ERROR 403: Forbidden.
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c mkdir nightly && cd nightly && wget -nv -O ifs.tar.gz https://s3-us-west-1.amazonaws.com/imageflow-nightlies/commits/${SOURCE_COMMIT}/linux64_glibc227.tar.gz     && tar xvzf ifs.tar.gz && mv ./imageflow_server ../ && cd .. && rm -rf nightly]: runc did not terminate sucessfully
```

**Comment by lilith** [comment]
You have to specify the full git commit (long version) for SOURCE_COMMIT to make it work.

**Comment by sanderkooger** [comment]
@lilith 

```
sander@TIF-NB-001:~/tif-repos/code/imageflow/docker/imageflow_server_unsecured$ docker build --build-arg SOURCE_COMMIT=66028603aeae6d9666bbfb7da83e026c14a8a660 --tag imazen/imageflow_server_unsecured:latest .
[+] Building 3.1s (6/7)                                                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.1s
 => => transferring dockerfile: 651B                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.1s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/imazen/imageflow_base_os:latest                                                                                                                             1.3s
 => CACHED [1/4] FROM docker.io/imazen/imageflow_base_os@sha256:1575c5707f7a09c45711328783c2cbfae4160ba8fc14ecef9d161a8e9da5750f                                                                       0.0s
 => [2/4] RUN if [ -z "66028603aeae6d9666bbfb7da83e026c14a8a660" ]; then echo "SOURCE_COMMIT not set; exiting" && exit 1; else echo "SOURCE_COMMIT=66028603aeae6d9666bbfb7da83e026c14a8a660"; fi       0.5s
 => ERROR [3/4] RUN mkdir nightly && cd nightly && wget -nv -O ifs.tar.gz https://s3-us-west-1.amazonaws.com/imageflow-nightlies/commits/66028603aeae6d9666bbfb7da83e026c14a8a660/linux64_glibc227.ta  1.2s
------
 > [3/4] RUN mkdir nightly && cd nightly && wget -nv -O ifs.tar.gz https://s3-us-west-1.amazonaws.com/imageflow-nightlies/commits/66028603aeae6d9666bbfb7da83e026c14a8a660/linux64_glibc227.tar.gz     && tar xvzf ifs.tar.gz && mv ./imageflow_server ../ && cd .. && rm -rf nightly:
#6 1.175 https://s3-us-west-1.amazonaws.com/imageflow-nightlies/commits/66028603aeae6d9666bbfb7da83e026c14a8a660/linux64_glibc227.tar.gz:
#6 1.175 2020-07-19 09:07:51 ERROR 403: Forbidden.
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c mkdir nightly && cd nightly && wget -nv -O ifs.tar.gz https://s3-us-west-1.amazonaws.com/imageflow-nightlies/commits/${SOURCE_COMMIT}/linux64_glibc227.tar.gz     && tar xvzf ifs.tar.gz && mv ./imageflow_server ../ && cd .. && rm -rf nightly]: runc did not terminate sucessfully
sander@TIF-NB-001:~/tif-repos/code/imageflow/docker/imageflow_server_unsecured$ 



```
Does no work File it needs to pull to build is not reachable .

**Comment by lilith** [comment]
That's because that build didn't complete all the way. Try 0ec50017343cd0481f04523f90f3f8fb5eb403ac

**Comment by aviatrix** [comment]
This is super useful setup, and I'm planning to use it, can we put these details in some wiki ?

**Comment by sanderkooger** [comment]
> This is super useful setup, and I'm planning to use it, can we put these details in some wiki ?

I would be more than willing to help make documentation on this implementation if you want.

**Comment by aviatrix** [comment]
@sanderkooger, even if it's in unofficial form i would love to have more details!

**Comment by lilith** [comment]
Documentation would be lovely!

**Comment by sanderkooger** [comment]
@lilith, We have just created a helm deployment chart, it deploys the container, had ingress configures and it creates a VPC and mounts it. 

I am documenting it now and we would love to share it with you. 

There is one thing we are still figuring out, If not started in demo mode. is there a livenessProbe probe and a readinessProbe probe we can use? Then Kubernetes is able to probe for all users that use the chart? 

```
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: / <================
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: / <===================
          #     port: http

```

**Comment by lilith** [comment]
Are there docs about what livenessProbe and readinessProbe endpoints should
return and when?

Also, have you considered using Imageflow.NET Server instead of
imageflow_server? We have dockerfiles for it also.

**Comment by lilith** [comment]
Nvm, I found the docs: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

I will work on adding these endpoints.

**Comment by lilith** [comment]
These are now available in Imageflow.NET Server: https://github.com/imazen/imageflow-dotnet-server/releases/tag/v0.5.3

I'll work on adding them to imageflow_server but that may take much longer

**Comment by sanderkooger** [comment]
Thank you Lillith!

Would you like me to push the helm deployment charts somewhere?

**Comment by lilith** [comment]
Yes, please. That would be great.

**Comment by sanderkooger** [comment]
Where would you like them. I can clean them up tomorow and publish

**Comment by lilith** [comment]
If you're targeting imageflow_server_unsecured, perhaps a PR to the https://github.com/imazen/imageflow/tree/main/docker/imageflow_server_unsecured folder and a mention in the readme? I have docker compose files in there now. 

If you're targeting Imageflow.NET Server, then maybe in https://github.com/imazen/imageflow-dotnet-server/tree/main/examples/Imageflow.Server.ExampleDocker ?

**Comment by sanderkooger** [comment]
I'm targeting imageflow server unsecured. I will start working on a PR ( Probably add a helm or a kubernetes directory)

**Comment by nathanchase** [comment]
I've been attempting to get `imazen/imageflow_server_unsecured:latest` running in an Azure Container Instance.

This is my deployment .yaml:
```
apiVersion: '2019-12-01'
location: eastus2
name: <name>
properties:
  containers:
  - name: <my-container-name>
    properties:
      environmentVariables:
        - name: 'RUST_BACKTRACE'
          value: '1'
      command: [ 
        "/bin/bash", 
        "-c", 
        "sudo chown -R imageflow /home/imageflow/ && /home/imageflow/imageflow_server start --bind-address 0.0.0.0 --port 80 --data-dir /home/imageflow/data/ --mount /images/:ir4_proxy_uncached:https:://" 
      ]
      image: imazen/imageflow_server_unsecured:latest
      ports:
      - port: 80
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
      volumeMounts:
      - mountPath: /home/imageflow/data/
        name: imageflow-cache
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
      - port: 80
    dnsNameLabel: <my-dns-label>
  volumes:
  - name: imageflow-cache
    azureFile:
      sharename: <my-storage-share-name>
      storageAccountName: <my-storage-account-name>
      storageAccountKey: <my-storage-key>
      readOnly: false
tags: {}
type: Microsoft.ContainerInstance/containerGroups
```
and this is the result when it deploys:
```
built 218 days ago - unofficial CI release build of v1.5.3-rc57-8-g9277047* (main) for x86_64-unknown-linux-gnu  (2020-12-02)
Listening on 0.0.0.0:80
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', imageflow_server/src/lib.rs:636:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: core::result::Result<T,E>::unwrap
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:973
   4: imageflow_server::serve
             at ./imageflow/imageflow_server/src/lib.rs:636
   5: imageflow_server::main_with_exit_code
             at ./imageflow/imageflow_server/src/main.rs:185
   6: imageflow_server::main
             at ./imageflow/imageflow_server/src/main.rs:14
   7: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I assume it has something to do with imageflow trying to use the Azure file share, but I'm not sure where I'm going wrong here in the syntax. 

I was using this as the guide on Azure ACIs: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files

And this (https://github.com/imazen/imageflow/blob/main/docker/imageflow_server_unsecured/docker-compose.yml) as the guide for what imageflow needs. 

Any ideas?
